-- TABLAS PARA EL SISTEMA DE BANCA

-- Crear tabla de clientes
CREATE TABLE "cliente" (
  "id_cliente" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(100),
  "email" varchar(120) UNIQUE,
  "telefono" varchar(20),
  "direccion" varchar(200)
);

-- Crear tabla de cuentas
CREATE TABLE "cuenta" (
  "id_cuenta" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cliente" int,
  "numero_cuenta" varchar(20) UNIQUE,
  "tipo" varchar(50),
  "saldo" numeric(12,2),
  "fecha_apertura" date
);

-- Crear tabla de tipos de transacción
CREATE TABLE "tipo_transaccion" (
  "id_tipo" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nombre" varchar(50),
  "descripcion" varchar(200)
);

-- Crear tabla de transacciones
CREATE TABLE "transaccion" (
  "id_transaccion" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "id_cuenta" int,
  "id_tipo" int,
  "fecha" timestamp,
  "monto" numeric(12,2),
  "descripcion" varchar(200)
);


-- Establecer relaciones entre tablas
ALTER TABLE "cuenta" ADD FOREIGN KEY ("id_cliente") REFERENCES "cliente" ("id_cliente");

ALTER TABLE "transaccion" ADD FOREIGN KEY ("id_cuenta") REFERENCES "cuenta" ("id_cuenta");

ALTER TABLE "transaccion" ADD FOREIGN KEY ("id_tipo") REFERENCES "tipo_transaccion" ("id_tipo");



-- INSERTAR DATOS --

-- Insertar clientes --
INSERT INTO "cliente" (id_cliente,nombre, email, telefono, direccion) VALUES
(1, 'Juan Pérez', 'juan.perez@gmail.com', '912345678', 'Av. Principal 123, Santiago'),
(2, 'María Gómez', 'maria.gomez@gmail.com', '987654321', 'Av. Los Libertadores 456, Valparaíso'),
(3, 'Carlos Rodríguez', 'carlos.rodriguez@gmail.com', '956789123', 'Av. San Francisco 789, Concepción'),
(4, 'Camila Rojas', 'camila.rojas@gmail.com', '934567890', 'Av. Balmaceda 123, Temuco');

SELECT * FROM "cliente";

-- Insertar cuentas --
INSERT INTO "cuenta" (id_cliente, numero_cuenta, tipo, saldo, fecha_apertura) VALUES
(1, '1234567890', 'Cuenta Corriente', 150000.00, '2024-01-15'),
(2, '0987654321', 'Cuenta Ahorro', 250000.00, '2024-02-28'),
(3, '1122334455', 'Cuenta Corriente', 35000.00, '2024-03-15'),
(4, '5566778899', 'Cuenta Ahorro', 75000.00, '2024-04-18');

SELECT * FROM "cuenta";

-- Insertar tipos de transacción --
INSERT INTO "tipo_transaccion" (nombre, descripcion) VALUES
('Depósito', 'Ingreso de dinero a la cuenta'),
('Retiro', 'Retiro de dinero de la cuenta'),
('Transferencia', 'Transferencia entre cuentas');

SELECT * FROM "tipo_transaccion";

-- Insertar transacciones --
INSERT INTO "transaccion" (id_cuenta, id_tipo, fecha, monto, descripcion) VALUES
(1, 1, '2025-10-22', 500.00, 'Depósito inicial'),
(1, 3, '2025-10-23', 15.99, 'Transferencia a cliente Carlos'),
(2, 1, '2025-10-24', 35.99, 'Depósito mensual'),
(3, 2, '2025-10-25', 7.99, 'Retiro en caja'),
(4, 1, '2025-10-26', 8.99, 'Depósito de intereses');

SELECT * FROM "transaccion";


-- CONSULTAS DE PRUEBA --

-- Consulta 1: Obtener el saldo de la cuenta de Juan Pérez --
SELECT c.nombre, cu.numero_cuenta, cu.saldo
FROM "cliente" c
JOIN "cuenta" cu ON c.id_cliente = cu.id_cliente
WHERE c.nombre = 'Juan Pérez';


-- Consulta 2: Listar todas las transacciones de la cuenta de María Gómez --
SELECT c.nombre, cu.numero_cuenta, t.fecha, tt.nombre AS tipo_transaccion, t.monto, t.descripcion
FROM "cliente" c
JOIN "cuenta" cu ON c.id_cliente = cu.id_cliente
JOIN "transaccion" t ON cu.id_cuenta = t.id_cuenta
JOIN "tipo_transaccion" tt ON t.id_tipo = tt.id_tipo
WHERE c.nombre = 'María Gómez';